[package]
name = "adsb-ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
surveillance-domain={path="../surveillance-domain"}

tokio = { version = "1", features = ["net", "rt-multi-thread", "macros"] }
bytes = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"